/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class TestTustedJNI */

#ifndef _Included_TestTustedJNI
#define _Included_TestTustedJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     TestTustedJNI
 * Method:    myNativeFunction
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_TestTustedJNI_myNativeFunction
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
